openapi: "3.0.1"
info: 
  title: "API MOSAIQUAGE"
  version: "1.0.0"
  description: "Documentation de l'API pour le controle et les retouches de mosaiquage."
servers: 
  - url: "http://localhost:8081"
    description: "Serveur de dev"
tags:
  - name: wmts
    description: Requête sur les tuiles
  - name: graph
    description: Modification du mosaïquage
paths:
  '/graph/patch':
    post:
      tags:
        - graph
      summary: "Application d'un patch de correction"
      description: ""
      requestBody:
       description: geoJson
       required: true
      #  content:
      #    application/json:
              # example: 
              #   projects:
              #     - name: Chantier 1
              #       jobs:
              #         - name: jobs 1
              #           command: touch file1
              #         - name: jobs 2
              #           command: touch file2
              #         - name: jobs 3
              #           command: touch file3
              #           deps:
              #             - id: 0
              #             - id: 1
              #     - name: Chantier 2
              #       jobs:
              #         - name: jobs 1
              #           command: touch file1
              #       deps:
              #         - id: 0
      responses:
        '200':
          description: OK
  '/graph':
    get:
      tags:
        - graph
      summary: "Récupération de l'identifiant du cliche"
      description: ""
      parameters:
        - in: query
          name: x
          description: x
          required: true
          schema:
            type: string
        - in: query
          name: y
          description: y
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  '/wmts':
    get:
      tags:
        - wmts
      summary: "service wmts pour ortho et graph"
      description: ""
      parameters:
        - in: query
          name: SERVICE
          required: true
          schema:
            type: string
            enum:
              - WMS
              - WMTS
        - in: query
          name: REQUEST
          required: true
          description: ""
          schema:
            type: string
            enum:
              - GetCapabilities
              - GetTile
              - GetFeatureInfo
        - in: query
          name: VERSION
          required: false
          schema:
            type: string
        - in: query
          name: LAYER
          required: false
          schema:
            type: string
        - in: query
          name: STYLE
          required: false
          schema:
            type: string
        - in: query
          name: FORMAT
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIXSET
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIX
          required: false
          schema:
            type: string
        - in: query
          name: TILEROW
          required: false
          schema:
            type: string
        - in: query
          name: TILECOL
          required: false
          schema:
            type: string
        - in: query
          name: I
          required: false
          schema:
            type: string
        - in: query
          name: J
          required: false
          schema:
            type: string
        - in: query
          name: INFOFORMAT
          required: false
          schema:
            type: string
  
      responses:
        '200':
          description: OK