openapi: "3.0.1"
info: 
  title: "API MOSAIQUAGE"
  version: "1.0.0"
  description: "Documentation de l'API pour le controle et les retouches de mosaiquage."
servers: 
  - url: "http://localhost:8081"
    description: "Serveur de dev"
tags:
  - name: wmts
    description: Requête sur les tuiles
  - name: graph
    description: Modification du mosaïquage

paths:
  '/graph/patch':
    post:
      tags:
        - graph
      summary: "Application d'un patch de correction"
      description: "Mise a jour du graph de mosaiquage a partir d'un geoJSON"
      requestBody:
        description: geoJson mettre a jour
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - FeatureCollection
                  crs:
                    type: object
                    example:
                      {
                        "type":"name",
                        "properties":{
                          "name":"urn:ogc:def:crs:EPSG::2154"}}

                  features:
                    type: object
                    example:
                      [ { type: 'Feature', properties: { color: [254, 175, 143], cliche: '19FD5606Ax00020_16371' }, geometry: { type: 'Polygon', coordinates: [Array] } } ]

      responses:
        '200':
          description: OK

  '/graph':
    get:
      tags:
        - graph
      summary: "Récupération de l'identifiant du cliche"
      description: ""
      parameters:
        - in: query
          name: x
          required: true
          schema:
            type: string
          example: 230975.84852638416
        - in: query
          name: y
          required: true
          schema:
            type: string
          example: 6759518.099720161
      responses:
        '200':
          description: OK

  '/wmts':
    get:
      tags:
        - wmts
      summary: "service wmts pour ortho et graph"
      description: ""
      parameters:
        - in: query
          name: SERVICE
          required: true
          schema:
            type: string
            enum:
              - WMS
              - WMTS
        - in: query
          name: REQUEST
          required: true
          description: ""
          schema:
            type: string
            enum:
              - GetCapabilities
              - GetTile
              - GetFeatureInfo
        - in: query
          name: VERSION
          description: ex: 1.0.0
          required: false
          schema:
            type: string
            pattern: '^\d+(.\d+)*$'
        - in: query
          description: required if GetTile
          name: LAYER
          required: false
          schema:
            type: string
        - in: query
          name: STYLE
          required: false
          schema:
            type: string
        - in: query
          name: FORMAT
          required: false
          schema:
            type: string
            enum:
              - image/png
              - image/jpeg
        - in: query
          name: TILEMATRIXSET
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIX
          required: false
          schema:
            type: string
        - in: query
          name: TILEROW
          required: false
          schema:
            type: string
        - in: query
          name: TILECOL
          required: false
          schema:
            type: string
        - in: query
          name: I
          required: false
          schema:
            type: string
        - in: query
          name: J
          required: false
          schema:
            type: string
        - in: query
          name: INFOFORMAT
          required: false
          schema:
            type: string
  
      responses:
        '200':
          description: OK



