openapi: "3.0.1"
info: 
  title: "API MOSAIQUAGE"
  version: "0.1.0"
  description: "Documentation de l'API pour le controle et les retouches de mosaiquage."
servers: 
  - url: "http://localhost:8081"
    description: "Serveur de dev"
tags:
  - name: wmts
    description: Requête sur les tuiles
  - name: graph
    description: Modification du mosaïquage

paths:
  '/graph/patch':
    post:
      tags:
        - graph
      summary: "Application d'un patch de correction"
      description: "Mise a jour du graph de mosaiquage a partir d'un geoJSON"
      requestBody:
        description: polygone à patcher (geoJson)
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - FeatureCollection
                  crs:
                    type: object
                    example:
                      {
                        "type":"name",
                        "properties":{
                          "name":"urn:ogc:def:crs:EPSG::2154"}}

                  features:
                    type: object
                    example:
                      [ { type: 'Feature', properties: { color: [254, 175, 143], cliche: '19FD5606Ax00020_16371' }, geometry: { type: 'Polygon', coordinates: [[[230748, 6759736], [230746, 6759736], [230746, 6759734], [230748, 6759734], [230748, 6759736]]] } } ]

      responses:
        '200':
          description: OK

  '/graph':
    get:
      tags:
        - graph
      summary: "Récupération de l'identifiant du cliche"
      description: ""
      parameters:
        - in: query
          name: x
          required: true
          schema:
            type: string
          example: 230975.8
        - in: query
          name: y
          required: true
          schema:
            type: string
          example: 6759518.1
      responses:
        '200':
          description: OK

  '/wmts':
    get:
      tags:
        - wmts
      summary: "service wmts pour ortho et graph"
      description: ""
      parameters:
        - in: query
          name: SERVICE
          required: true
          schema:
            type: string
            enum:
              - WMS
              - WMTS
        - in: query
          name: REQUEST
          required: true
          description: ""
          schema:
            type: string
            enum:
              - GetCapabilities
              - GetTile
              - GetFeatureInfo
        - in: query
          name: VERSION
          description: ex: 1.0.0
          required: false
          schema:
            type: string
            pattern: '^\d+(.\d+)*$'
        - in: query
          name: LAYER
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: STYLE
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: FORMAT
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
            enum:
              - image/png
              - image/jpeg
        - in: query
          name: TILEMATRIXSET
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIX
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: TILEROW
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: TILECOL
          description: required if GetTile or GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: I
          description: required if GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: J
          description: required if GetFeatureInfo
          required: false
          schema:
            type: string
        - in: query
          name: INFOFORMAT
          description: required if GetFeatureInfo
          required: false
          schema:
            type: string
  
      responses:
        '200':
          description: OK

  '/json/{filetype}':
    get:
      tags:
        - files
      summary: "Récupération des fichiers json pour iTowns"
      description: "Route permettant la récupération des 3 fichiers json ncessaires à l'execution de la partie iTowns"
      parameters:
        - in: path
          name: filetype
          required: true
          schema:
            type: string
            enum:
              - graph
              - ortho
              - opi

      responses:
        '200':
          description: OK

