openapi: "3.0.1"
info: 
  title: "API MOSAIQUAGE"
  version: "1.0.0"
  description: "Documentation de l'API pour le controle et les retouches de mosaiquage."
servers: 
  - url: "http://localhost:8081"
    description: "Serveur de dev"
tags:
  - name: wmts
    description: Requête sur les tuiles
  - name: edit
    description: Modification du mosaïquage
paths:
  '/wmts':
    get:
      tags:
        - wmts
      summary: "service wmts pour ortho et graph"
      description: ""
      parameters:
        - in: query
          name: SERVICE
          required: true
          schema:
            type: string
        - in: query
          name: VERSION
          required: true
          schema:
            type: string
        - in: query
          name: REQUEST
          required: true
          schema:
            type: string
        - in: query
          name: LAYER
          required: false
          schema:
            type: string
        - in: query
          name: STYLE
          required: false
          schema:
            type: string
        - in: query
          name: FORMAT
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIXSET
          required: false
          schema:
            type: string
        - in: query
          name: TILEMATRIX
          required: false
          schema:
            type: string
        - in: query
          name: TILEROW
          required: false
          schema:
            type: string
        - in: query
          name: TILECOL
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK