name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
    - name: install
      run: npm install
    - name: test
      env:
        DEBUG: wmts,graph
      shell: bash -l {0}
      run: |
        conda init bash
        conda create -n test -c conda-forge gdal
        conda activate test
        npm run test-coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
