name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
    - name: conda install
      run: |
        conda init bash
        conda create -n test -c conda-forge gdal
        conda activate test
        python3 scripts/GetColor.py -C cache/17 -X 200 -Y 200 -l graph.png -i 100 -j 100
        which python3

    - name: install
      run: npm install
    - name: test
      env:
        DEBUG: wmts,graph
      run: |
        npm run test-coveralls
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
