name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm install
      
    - name: test
      env:
        DEBUG: patch
      run: npx mocha test -c cache_test
      
    - name: test coveralls
      env:
        DEBUG: patch
      run: |
        git checkout cache_test
        npm run test-coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
