# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.6
        conda-channels: anaconda, conda-forge
        
    - name: Create conda env
      run: |
        conda env create -f environment.yml
        conda activate mosaique
  
    - name: Use Node.js
      uses: actions/setup-node@v1
      
    - name: API Install dependencies
      run: npm install
        
    - name: API Run lint
      run: npm run lint
